// <auto-generated />
using System;
using FlytoHome.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlytoHome.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlytoHome.Models.Acasalamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataUniao")
                        .HasColumnType("datetime2");

                    b.Property<int>("FemeaId")
                        .HasColumnType("int");

                    b.Property<int>("FilhotesNascidos")
                        .HasColumnType("int");

                    b.Property<int>("MachoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PrevisaoNascimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuantidadeOvos")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FemeaId");

                    b.HasIndex("MachoId");

                    b.ToTable("Acasalamentos");
                });

            modelBuilder.Entity("FlytoHome.Models.Competicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<double>("Distancia")
                        .HasColumnType("float");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Competicoes");
                });

            modelBuilder.Entity("FlytoHome.Models.Pombo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Anilha")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaeId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaiId")
                        .HasColumnType("int");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Anilha")
                        .IsUnique();

                    b.HasIndex("MaeId");

                    b.HasIndex("PaiId");

                    b.ToTable("Pombos");
                });

            modelBuilder.Entity("FlytoHome.Models.RegistroSaude", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PomboId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProximaDose")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PomboId");

                    b.ToTable("RegistrosSaude");
                });

            modelBuilder.Entity("FlytoHome.Models.ResultadoCompeticao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompeticaoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PomboId")
                        .HasColumnType("int");

                    b.Property<int?>("Posicao")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Tempo")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("CompeticaoId");

                    b.HasIndex("PomboId");

                    b.ToTable("ResultadosCompeticao");
                });

            modelBuilder.Entity("FlytoHome.Models.Acasalamento", b =>
                {
                    b.HasOne("FlytoHome.Models.Pombo", "Femea")
                        .WithMany("AcasalamentosComFemea")
                        .HasForeignKey("FemeaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlytoHome.Models.Pombo", "Macho")
                        .WithMany("AcasalamentosComMacho")
                        .HasForeignKey("MachoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Femea");

                    b.Navigation("Macho");
                });

            modelBuilder.Entity("FlytoHome.Models.Pombo", b =>
                {
                    b.HasOne("FlytoHome.Models.Pombo", "Mae")
                        .WithMany()
                        .HasForeignKey("MaeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlytoHome.Models.Pombo", "Pai")
                        .WithMany()
                        .HasForeignKey("PaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Mae");

                    b.Navigation("Pai");
                });

            modelBuilder.Entity("FlytoHome.Models.RegistroSaude", b =>
                {
                    b.HasOne("FlytoHome.Models.Pombo", "Pombo")
                        .WithMany("RegistrosSaude")
                        .HasForeignKey("PomboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pombo");
                });

            modelBuilder.Entity("FlytoHome.Models.ResultadoCompeticao", b =>
                {
                    b.HasOne("FlytoHome.Models.Competicao", "Competicao")
                        .WithMany("Resultados")
                        .HasForeignKey("CompeticaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlytoHome.Models.Pombo", "Pombo")
                        .WithMany("Resultados")
                        .HasForeignKey("PomboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competicao");

                    b.Navigation("Pombo");
                });

            modelBuilder.Entity("FlytoHome.Models.Competicao", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("FlytoHome.Models.Pombo", b =>
                {
                    b.Navigation("AcasalamentosComFemea");

                    b.Navigation("AcasalamentosComMacho");

                    b.Navigation("RegistrosSaude");

                    b.Navigation("Resultados");
                });
#pragma warning restore 612, 618
        }
    }
}
